name: flow

on:
  push:
    branches:
      - main
      
permissions:
      id-token: write
      contents: read
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Check Azure CLI
      run: |
        az --version

    - name: Az CLI login
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build and Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: <your-azure-app-name>
        slot-name: production
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
        package: FastAPI_backend
        
