name: flow

on:
  push:
    branches:
      - main
      
permissions:
  id-token: write
  contents: read
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1 
      with:
        registry: backregistry.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: ./front/dockerfile
        push: true
        tags: backregistry.azurecr.io/front:${{ github.sha }}

        
