name: flow

on:
  push:
    branches:
      - main
      
permissions:
      id-token: write
      contents: read
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check Azure CLI
      run: |
        az --version

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app.py'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: '.'
        
